
 export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
 export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'
 export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
 export const GET_PRODUCTSINGLE_SUCCESS = 'GET_PRODUCTSINGLE_SUCCESS'



 export const AUTH_REQUEST = 'AUTH_REQUEST'
 export const AUTH_FAILURE = 'AUTH_FAILURE'
 export const POST_AUTH_SUCCESS = 'POST_AUTH_SUCCESS'
 


 export const CART_PRODUCT_REQUEST = 'CART_PRODUCT_REQUEST'
 export const PATCH_CART_PRODUCT_SUCCESS = 'PATCH_CART_PRODUCT_SUCCESS'
 export const CART_PRODUCT_FAILURE = 'CART_PRODUCT_FAILURE'