
 export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
 export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'
 export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'



 export const AUTH_REQUEST = 'AUTH_REQUEST'
 export const AUTH_FAILURE = 'AUTH_FAILURE'
 export const POST_AUTH_SUCCESS = 'POST_AUTH_SUCCESS'
 